# Generated by Django 4.1.7 on 2023-03-11 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_user_birthdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
