# Generated by Django 4.1.7 on 2023-03-18 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Right',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('defaultState', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=24)),
                ('email', models.EmailField(max_length=254)),
                ('about', models.CharField(max_length=512)),
                ('birthDate', models.DateField()),
                ('dateCreate', models.DateField(auto_now_add=True)),
                ('isBlocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserRight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isActive', models.BooleanField(default=False)),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.right')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='media/user/avatar')),
                ('background', models.ImageField(upload_to='media/user/background')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user')),
            ],
        ),
    ]
