# Generated by Django 4.1.7 on 2023-03-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
