# Generated by Django 4.1.7 on 2023-03-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_alter_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userphoto',
            name='avatar',
            field=models.ImageField(upload_to='user/avatar'),
        ),
        migrations.AlterField(
            model_name='userphoto',
            name='background',
            field=models.ImageField(upload_to='user/background'),
        ),
    ]
