# Generated by Django 4.2 on 2023-05-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_userdata_alter_userphoto_user_alter_userright_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='right',
            old_name='defaultState',
            new_name='default_state',
        ),
        migrations.RenameField(
            model_name='userdata',
            old_name='birthDate',
            new_name='birth_date',
        ),
        migrations.RenameField(
            model_name='userright',
            old_name='isActive',
            new_name='is_active',
        ),
    ]
