# Generated by Django 4.1.7 on 2023-03-23 03:38

from django.db import migrations, models
import jam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('theme', models.CharField(max_length=128, unique=True)),
                ('avatar', models.ImageField(upload_to='media/jam/avatar')),
            ],
        ),
        migrations.CreateModel(
            name='JamCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            bases=(models.Model, ),
        ),
        migrations.CreateModel(
            name='JamDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('votingStartDate', models.DateField()),
                ('votingEndDate', models.DateField()),
            ],
            bases=(models.Model, ),
        ),
    ]
