# Generated by Django 4.1.7 on 2023-03-23 04:55

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jam',
            name='content',
            field=tinymce.models.HTMLField(default=''),
        ),
    ]
