# Generated by Django 4.1.7 on 2023-03-26 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0002_jam_content'),
    ]

    operations = [
    ]
