# Generated by Django 4.1.7 on 2023-03-26 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0003_remove_jam_content'),
    ]

    operations = [
    ]
