# Generated by Django 4.1.7 on 2023-03-26 07:55

from django.db import migrations
from django_ckeditor_5.fields import CKEditor5Field


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0004_jam_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='jam',
            name='content',
            field=CKEditor5Field(config_name='extends'),
        ),
    ]
