# Generated by Django 4.1.7 on 2023-03-29 05:58

import ckeditor_uploader.fields
from django.db import migrations, models
import jam.models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0005_jam_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='JamColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('backgroundColor', models.CharField(max_length=10)),
                ('formColor', models.CharField(max_length=10)),
                ('mainTextColor', models.CharField(max_length=10)),
            ],
            bases=(models.Model,),
        ),
        migrations.AlterField(
            model_name='jam',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
        migrations.AlterField(
            model_name='jam',
            name='theme',
            field=models.CharField(max_length=128),
        ),
    ]
