# Generated by Django 4.1.7 on 2023-03-29 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0006_jamcolor_alter_jam_content_alter_jam_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jamcolor',
            name='startDate',
        ),
    ]
