# Generated by Django 4.1.7 on 2023-03-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0007_remove_jamcolor_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamdate',
            name='startDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jamdate',
            name='votingEndDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jamdate',
            name='votingStartDate',
            field=models.DateTimeField(),
        ),
    ]
