# Generated by Django 4.1.7 on 2023-03-30 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0008_alter_jamdate_startdate_alter_jamdate_votingenddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamcolor',
            name='jam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jam.jam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jamcriteria',
            name='jam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jam.jam'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jamdate',
            name='jam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='jam.jam'),
            preserve_default=False,
        ),
    ]
