# Generated by Django 4.1.7 on 2023-04-04 09:05

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_alter_userphoto_avatar_alter_userphoto_background'),
        ('jam', '0010_alter_jam_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isTeam', models.BooleanField(default=True)),
                ('jam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jam.jam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.user')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('link', models.CharField(max_length=512, unique=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jam.participant')),
            ],
        ),
    ]
