# Generated by Django 4.1.7 on 2023-04-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0013_alter_jamdate_startdate_alter_jamdate_votingenddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamdate',
            name='startDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jamdate',
            name='votingStartDate',
            field=models.DateTimeField(),
        ),
    ]
