# Generated by Django 4.1.7 on 2023-04-14 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0014_alter_jamdate_startdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamdate',
            name='votingEndDate',
            field=models.DateTimeField(),
        ),
    ]
