# Generated by Django 4.1.7 on 2023-04-14 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0015_alter_jamdate_votingenddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamdate',
            name='startDate',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jamdate',
            name='votingEndDate',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jamdate',
            name='votingStartDate',
            field=models.CharField(max_length=30),
        ),
    ]
