# Generated by Django 4.1.7 on 2023-04-23 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0017_jam_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamcriteria',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
