# Generated by Django 4.2 on 2023-04-25 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0018_alter_jamcriteria_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamdate',
            name='timeZone',
            field=models.CharField(default='Asia/Krasnoyarsk', max_length=30),
        ),
    ]
