# Generated by Django 4.2 on 2023-05-02 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0019_jamdate_timezone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jamcolor',
            old_name='backgroundColor',
            new_name='background_color',
        ),
        migrations.RenameField(
            model_name='jamcolor',
            old_name='formColor',
            new_name='form_color',
        ),
        migrations.RenameField(
            model_name='jamcolor',
            old_name='mainTextColor',
            new_name='mainText_color',
        ),
        migrations.RenameField(
            model_name='jamdate',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='jamdate',
            old_name='timeZone',
            new_name='time_zone',
        ),
        migrations.RenameField(
            model_name='jamdate',
            old_name='votingEndDate',
            new_name='voting_end_date',
        ),
        migrations.RenameField(
            model_name='jamdate',
            old_name='votingStartDate',
            new_name='voting_start_date',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='isTeam',
            new_name='is_team',
        ),
    ]
