# Generated by Django 4.2 on 2023-05-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0020_rename_backgroundcolor_jamcolor_background_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jamcolor',
            old_name='mainText_color',
            new_name='main_text_color',
        ),
    ]
