# Generated by Django 4.2 on 2023-05-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0021_rename_maintext_color_jamcolor_main_text_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamdate',
            name='start_date',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jamdate',
            name='time_zone',
            field=models.CharField(default='Asia/Krasnoyarsk', max_length=30),
        ),
        migrations.AlterField(
            model_name='jamdate',
            name='voting_end_date',
            field=models.DateField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jamdate',
            name='voting_start_date',
            field=models.DateField(max_length=30),
        ),
    ]
