# Generated by Django 4.2 on 2023-05-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0022_alter_jamdate_start_date_alter_jamdate_time_zone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamdate',
            name='time_zone',
            field=models.CharField(default='Asia/Krasnoyarsk', max_length=30),
        ),
    ]
