# Generated by Django 4.2 on 2023-05-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0023_alter_jamdate_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamdate',
            name='start_date',
            field=models.DateTimeField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jamdate',
            name='voting_end_date',
            field=models.DateTimeField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jamdate',
            name='voting_start_date',
            field=models.DateTimeField(max_length=30),
        ),
    ]
