# Generated by Django 4.2 on 2023-05-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0024_alter_jamdate_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamdate',
            name='start_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jamdate',
            name='voting_end_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='jamdate',
            name='voting_start_date',
            field=models.CharField(max_length=30),
        ),
    ]
