# Generated by Django 4.2 on 2023-05-06 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0025_alter_jamdate_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='project',
            name='link',
        ),
        migrations.AddField(
            model_name='project',
            name='avatar',
            field=models.ImageField(default='', upload_to='jam/project/avatar'),
        ),
        migrations.AlterField(
            model_name='project',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jam.participant'),
        ),
        migrations.CreateModel(
            name='ProjectColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(max_length=10)),
                ('form_color', models.CharField(max_length=10)),
                ('main_text_color', models.CharField(max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jam.project')),
            ],
        ),
    ]
