# Generated by Django 4.2.1 on 2023-05-13 09:14

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jam', '0029_alter_jam_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jam',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
