# Generated by Django 4.2.1 on 2023-05-11 03:45

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jam', '0027_remove_projectcolor_project_delete_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('avatar', models.ImageField(default='', upload_to='jam/project/avatar')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(default='')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jam.participant')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(max_length=10)),
                ('form_color', models.CharField(max_length=10)),
                ('main_text_color', models.CharField(max_length=10)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project')),
            ],
        ),
    ]
