# Generated by Django 4.2.1 on 2023-05-15 15:02

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
